on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
  push:    
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platforms: 'linux/amd64,linux/arm64'
            tag-latest: 'false'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: p-v-a/sip-in-container

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - run: |
        ls -la . .git/modules/SIP
        git status
        git --git-dir=.git/modules/SIP rev-list --count HEAD
        git submodule status

    - name: Prepare
      id: prepare
      run: |
          CURRENT_REVISION=$(git --git-dir=.git/modules/SIP rev-list --count HEAD)
          BASE_REVISION=1073
          REVISION=$(($CURRENT_REVISION-$BASE_REVISION ))
          VERSION=5.0.${REVISION}

          echo "tag=${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VERSION}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ${{ steps.prepare.outputs.tag }}
